language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: fa10e005ac84842738d7ccab78689e3b78f655b0
  keep-history: true
  on:
    branch: master
